### ISSUE TITLE
BatchLoaderWithContext causes java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by oonxt** [Netflix/dgs-framework#120]
The file ExampleLoaderWithContext.java from example.

errors:
java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)'
	at com.netflix.graphql.dgs.internal.DgsDataLoaderProvider$createDataLoader$options$1.<init>(DgsDataLoaderProvider.kt) ~[graphql-dgs-3.7.1.jar:3.7.1]
	at com.netflix.graphql.dgs.internal.DgsDataLoaderProvider.createDataLoader(DgsDataLoaderProvider.kt:145) ~[graphql-dgs-3.7.1.jar:3.7.1]
	at com.netflix.graphql.dgs.internal.DgsDataLoaderProvider.buildRegistryWithContextSupplier(DgsDataLoaderProvider.kt:54) ~[graphql-dgs-3.7.1.jar:3.7.1]
	at com.netflix.graphql.dgs.internal.DefaultDgsQueryExecutor.execute(DefaultDgsQueryExecutor.kt:100) ~[graphql-dgs-3.7.1.jar:3.7.1]
	at com.netflix.graphql.dgs.internal.DefaultDgsQueryExecutor.execute(DefaultDgsQueryExecutor.kt:78) ~[graphql-dgs-3.7.1.jar:3.7.1].

am i missing something?

**Comment by TGNThump** [comment]
I'm also seeing this issue (not just with the example file). Bumping the kotlin version to 1.4 seems to be a workaround, but given Spring Boot doesn't officially support Kotlin 1.4, I'm not sure that's the best approach.

**Comment by paulbakker** [comment]
The framework is using the latest (currently 1.4.31) Kotlin version, which works fine with Spring Boot. 

I'm curious how you got this issue though - did you specify Kotlin 1.3 explicitly somewhere?

**Comment by paulbakker** [comment]
Btw, I tried creating a new Spring Boot project through the Spring Initizlizr, and it uses Kotlin 1.4:
```
kotlin("jvm") version "1.4.30"
kotlin("plugin.spring") version "1.4.30"
```

**Comment by TGNThump** [comment]
I was inheriting <kotlin.version>1.3.61</kotlin.version> from spring-boot-dependencies v2.2.4.RELEASE.
It might be worth specifying a minimum supported Spring Boot version in the docs.

The [latest Spring Framework docs](https://docs.spring.io/spring-framework/docs/current/reference/html/languages.html#languages) say "Spring Framework supports Kotlin 1.3", which is why I assumed that 1.4 wasn't supported officially.

**Comment by paulbakker** [comment]
Right ok, that clears things up somewhat. I agree we should be clear about expected Spring Boot and Kotlin dependencies. This is the first time running into something like this, so w also didn't explicitly know which versions we support.

I'll add a note to the docs.

**Comment by paulbakker** [comment]
Docs fix here: https://github.com/Netflix/dgs/commit/f5460333a634134c6b953040ce29b2a7d94febe9
