### ISSUE TITLE
bug: [DgsQueryExecutor] HttpHeaders are not being processed

### ISSUE THREAD

**Issue by MessiasLima** [Netflix/dgs-framework#1268]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior
When I am writing tests using `DgsQueryExecutor`, and passing a http header. That header should be processed by Spring boot and be available on the data fetcher if necessary.

## Actual behavior
The headers are ignored and the requested header is null on test cases.

## Steps to reproduce
1. Retrieve some header on fetcher class: 
```kotlin
@DgsComponent
class MyDataFetcher {
    @DgsQuery
    fun getSomeDataUsingHeader(
        @RequestHeader(HttpHeaders.AUTHORIZATION) authorization: String,
    ): ChatAuthorizationResponse {
        // do some stuff using the authorization token
    }
}

```
2. Pass the header on a test case
```kotlin
@SpringBootTest(
    classes = [
        DgsAutoConfiguration::class,
        DgsExtendedScalarsAutoConfiguration::class,
        UUIDScalar::class,
        MyDataFetcher::class,
    ]
)
internal class MyDataFetcher {
    @Autowired
    lateinit var dgsQueryExecutor: DgsQueryExecutor

    @Test
    fun `chat query successfully`() {
        val gqlRequest = // request creation 

        val headers = HttpHeaders().apply {
            setBearerAuth("abc123")
        }

        val response = dgsQueryExecutor.executeAndExtractJsonPath<ChatAuthorizationResponse>(
            gqlRequest.serialize(),
            "data",
            headers,
        )

        // Assertions
    }
}
```
3. You will get this error when running the test
```
java.lang.NullPointerException: Parameter specified as non-null is null: method package.ommited.MyDataFetcher.getSomeDataUsingHeader, parameter authorization
	at package.ommited.MyDataFetcher.getSomeDataUsingHeader(MyDataFetcher.kt) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282) ~[spring-core-5.3.23.jar:5.3.23]
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.get(DataFetcherInvoker.kt:68) ~[graphql-dgs-5.2.4.jar:5.2.4]
	at graphql.schema.DataFetcherFactories.lambda$wrapDataFetcher$2(DataFetcherFactories.java:37) ~[graphql-java-19.2.jar:na]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:282) ~[graphql-java-19.2.jar:na]
```

**Comment by ClaudenirFreitas** [comment]
This incident is happening because there is no `HandlerMethodArgumentResolverAdapter` instance.   
We can create it by adding the `DgsWebMvcAutoConfiguration` class e.g:
```java
@SpringBootTest(
    classes = [
        DgsAutoConfiguration::class,
        DgsWebMvcAutoConfiguration::class,
        DgsExtendedScalarsAutoConfiguration::class,
        UUIDScalar::class,
        MyDataFetcher::class,
    ]
)
```
But there is another issue with this approach where [servletWebRequest argument is null](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/DefaultDgsQueryExecutor.kt#L164). So, [this piece of code](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-spring-webmvc/src/main/kotlin/com/netflix/graphql/dgs/mvc/internal/method/HandlerMethodArgumentResolverAdapter.kt#L51) will throw a `NullPointerException`.

I am trying to find an elegant approach to fix it.

**Comment by ClaudenirFreitas** [comment]
Unfortunately, it is a bug. 
I just created [this branch](https://github.com/Netflix/dgs-framework/compare/master...ClaudenirFreitas:dgs-framework:bugfix/issue-1268-fix-query-executor-with-http-headers) to validate [this comment](https://github.com/Netflix/dgs-framework/issues/1268#issuecomment-1366908934).  
Does it make sense @paulbakker @srinivasankavitha ?

**Comment by rorychatterton** [comment]
@MessiasLima or @ClaudenirFreitas, have you had any luck finding a workaround for this.

We're developing an app with DGS at the moment and are a little stuck with our testing because we are unable to fake our standard tenant context header.

**Comment by MessiasLima** [comment]
> @MessiasLima or @ClaudenirFreitas, have you had any luck finding a workaround for this?
> 
> We're developing an app with DGS at the moment and are a little stuck with our testing because we are unable to fake our standard tenant context header.

Unfortunately not. In order to not let it be totally untested, we decided to not use the Spring/DGS testing tools and tested it like a normal JUnit test. We are passing the data directly to the method.
```kotlin
@Test
fun `should do some stuff`() {
    val testHeader = "test-header"
    val actual = dataFetcherUnderTest.doSomeStuff(testHeader)
    assertThat(actual).isSomethingUseful()
}
```

I know that its not the best way, but its better than testing nothing

**Comment by Vyse777** [comment]
Dang, I just hit this issue today as well! Has there been any update on this by chance?

The recommendation above works for testing I suppose, but doing so completely eliminates the entire purpose of this documentation for people who intend to extract data from request headers:
https://netflix.github.io/dgs/query-execution-testing/#building-graphql-queries-for-tests

**Comment by Vyse777** [comment]
Also, more importantly is there anything I could do to help resolve this?
It is open-source after all 😃

**Comment by congotej** [comment]
@Vyse777 We do accept contributions, so feel free to open a PR if you need this. We won't be able to get to it during the next few months at least unfortunately.

**Comment by srinivasankavitha** [comment]
I've added a few more test cases to validate this works correctly: https://github.com/Netflix/dgs-framework/commit/f182efd7bfd12e24a498cf091a629d405e8f2369

Please take a look to see if you are missing anything in comparison.

I've also updated our docs to specify adding the `DgsWebMvcAutoConfiguration.class` in the list of classes with `@SpringBootTest`. This is essential for tests that are validating datafetchers using `@RequestHeader` etc.

**Comment by Vyse777** [comment]
> I've added a few more test cases to validate this works correctly: https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-example-java/src/test/java/RequestHeaderDataFetcherTest.java#L43
> 
> Please take a look to see if you are missing anything in comparison.
> 
> I've also updated our docs to specify adding the `DgsWebMvcAutoConfiguration.class` in the list of classes with `@SpringBootTest`. This is essential for tests that are validating datafetchers using `@RequestHeader` etc.

This actually works great and solves my issue as well. Thanks for including two possible testing examples, one where you use a full `MockHttpServletRequest` and another where you just pass headers.

This works for me!
