### ISSUE TITLE
bug: 5.4.0 does not properly upgrade grapqhl-java to 19.0

### ISSUE THREAD

**Issue by EugenMayer** [Netflix/dgs-framework#1281]
Considering the release notes, it should be upgraded to 19.0, but for me it is still on 18.3, leading to issues like.

- Gradle 7.5.1 
-  Java 17
- netflix dgs 5.4.0
- spring boot 2.7.4

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'schema' threw exception; nested exception is java.lang.NoSuchMethodError: 'graphql.schema.idl.RuntimeWiring graphql.schema.idl.RuntimeWiring.transform(java.util.function.Consumer)'
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 78 more
Caused by: java.lang.NoSuchMethodError: 'graphql.schema.idl.RuntimeWiring graphql.schema.idl.RuntimeWiring.transform(java.util.function.Consumer)'
	at com.apollographql.federation.graphqljava.Federation.ensureFederationDirectiveDefinitionsExist(Federation.java:194)
	at com.apollographql.federation.graphqljava.Federation.transform(Federation.java:67)
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider.computeSchema(DgsSchemaProvider.kt:184)
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider.schema(DgsSchemaProvider.kt:122)
	at com.netflix.graphql.dgs.autoconfig.DgsAutoConfiguration.schema(DgsAutoConfiguration.kt:206)
```

Currently using this to fix that

```
dependencyManagement {
    dependencies {
        // FIXME: Fixing open CVEs - remove when the transitive dependencies have been updated
        dependency "org.yaml:snakeyaml:1.33"
        dependency "net.datafaker:datafaker:1.6.0"
        dependency "com.google.protobuf:protobuf-java:3.21.7"
        dependency "com.graphql-java:java-dataloader:3.2.0"
       	// Fix netflix dgs graqphl java update
        dependency "com.graphql-java:graphql-java:19.2"
        dependency "com.graphql-java:graphql-java-extended-scalars:19.0"
    }
}

```

**Comment by srinivasankavitha** [comment]
Where do you see 18.3 getting pulled in? We've tried this on a few apps and seems to work ok.

**Comment by EugenMayer** [comment]
@srinivasankavitha which spring boot version are you using? I can see that it is resolved via `:dependencies` and also the OWASP dep scanner triggers due to the outdated (18.3) gql java extended scalars.

**Comment by srinivasankavitha** [comment]
Spring Boot 2.6 is what we are using/

**Comment by berngp** [comment]
@EugenMayer, you are most likely using Spring's `dependency-management` Gradle Plugin. This will force the GraphQL Java version to 18.[2,3]. Ref [F.1. Managed Dependency Coordinates](https://docs.spring.io/spring-boot/docs/2.7.4/reference/htmlsingle/#appendix.dependency-versions.properties).

You can work around this by either...

## Explicit graphql-java.version for the dependency-management

```
// for kotlin files
extra["graphql-java.version"] = "19.2"
```
or 
```
// for groovy files
ext['graphql-java.version'] = '19.2'
```

This option is not ideal since you now have to manage the GraphQL Java Version.

## Use DGS Platform as a Imported BOM for the SB Dependency Management Plugin

Import the DGS Platform BOM such that the SB Dependency Management Plugin respects the versions expressed by the DGS BOM. e.g.

```
dependencyManagement {
    imports {
        mavenBom("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:latest.release")
    }
}
```

e.g. https://github.com/Netflix/dgs-examples-java/pull/102

**Comment by EugenMayer** [comment]
What we use is

```
dependencies {
  implementation(
	platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:${netflixDgs}"),
  }
}
```

are you explicitly suggesting to move this into dependencyManagement? Using your above works and fixes the issue. I guess doing what we did with platform is just wrong then?

**Comment by srinivasankavitha** [comment]
@EugenMayer - What you had previously was not wrong. It is still valid syntax. Rather the 2.7 release of the SB dependency management plugin forces the graphql-java version to `18.3` and therefore we need to use the format with imports to override that behavior. Previously, the SB dependency management plugin did not enforce this version, so we were not running into issues. So this format is recommended if you are using 
```
plugins {
   ...
    id("io.spring.dependency-management") version "1.0.12.RELEASE"
}
```
Prior to our update to graphql-java-19, this was matching and was not an issue. But now we are not aligned. Once the SB dep management plugin updates, this probably would not be an issue (until we update again causing a mismatch).

I will update our docs to reflect this.

**Comment by UglyHobbitFeet** [comment]
> ext['graphql-java.version']

Unfortunately neither of these commands work for a machine that is disconnected from the internet. Is there a workaround for offline machines?

**Comment by berngp** [comment]
@UglyHobbitFeet...
* Is the task/project that defines the offline repo producing a repo with graphql-java 19.2? 
* Could you include a sample of the build.gradle file that creates the offline repo?

**Comment by UglyHobbitFeet** [comment]
> * graphql-java 19.2

- Yes, as an example, the .m2 repo has a com/graphql-java/graphql-java/19.2 folder with contents
- A sample task has been provided in the link in the original comment

**Comment by srinivasankavitha** [comment]
We'll need to update our codegen to also use the latest graphql-java version. Will update and do a release.

**Comment by berngp** [comment]
@srinivasankavitha, I'm still not sure why the version in the plugin will downgrade it to 18.3 instead of giving priority to the higher 19.2 version.

**Comment by berngp** [comment]
For example, in [this dgs-examples-java PR](https://github.com/Netflix/dgs-examples-java/pull/102) the `graphql-java` version expressed by the plugin is getting bumped to the later 19.2
```
+--- com.netflix.graphql.dgs.codegen:graphql-dgs-codegen-shared-core:5.2.4
|    +--- com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:5.0.4
|    |    ...
|    +--- org.jetbrains.kotlin:kotlin-reflect:1.7.0 -> 1.6.21 (*)
|    +--- com.graphql-java:graphql-java:18.1 -> 19.2 (*)
|    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.0 -> 1.6.21 (*)
```

**Comment by miles-po** [comment]
This still appears to be a problem. Using DGS version 5.4.3 with Spring Boot 2.7.5. Using Maven, not Gradle.
```sh
mvn dependency:tree
```
returns
```
...
|  +- com.netflix.graphql.dgs:graphql-dgs-client:jar:5.4.3:compile
|  |  +- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.13.4:compile
|  |  \- com.graphql-java:graphql-java:jar:18.3:compile
|  |     +- com.graphql-java:java-dataloader:jar:3.1.2:compile
|  |     \- org.antlr:antlr4-runtime:jar:4.9.3:runtime
...
```
This is the only place in the dependency tree that `com.graphql-java:graphql-java` appears. v19.2 is nowhere to be seen. I tried clearing out the .m2 directory as well. Still pegged to 18.3. I'd prefer not adding an exclusion if possible so that dependent libraries can be kept in sync more easily for version upgrades.

**Comment by noorul** [comment]
This is still a problem with Maven. Can we re-open this ticket?

**Comment by noorul** [comment]
This is still a problem with Maven. Can we re-open this ticket?

**Comment by bcole** [comment]
This is a problem for us too, with Maven.  We do use `graphql-dgs-platform-dependencies` dependencyManagement.  It worked in previous versions, but when we upgrade to `5.4.0` we start seeing the same `java.lang.NoSuchMethodError`.

I ran a `mvn dependency:tree -Dverbose`.  You can see a few:
```
[INFO] |  |  |  |  +- (com.graphql-java:graphql-java:jar:18.3:compile - version managed from 19.2; omitted for duplicate)
```
and also:
```
[INFO] |  |  +- com.graphql-java:graphql-java:jar:18.3:compile (version managed from 19.2; scope not updated to compile)
```
under the `graphql-dgs-extended-scalars` library that we are also using.

It almost seems like `graphql-dgs-extended-scalars` somehow is causing an issue of resolving to 18.3 rather than 19.2?  Not too sure.  Here is a more full `mvn dependency:tree -Dverbose` output (removed some irrelevant dependencies):
```
[INFO] Building MyApp 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:3.4.0:tree (default-cli) @ my-app ---
[INFO] com.mytestapp:my-app:jar:0.0.1-SNAPSHOT
[INFO] +- com.mytestapp:my-test-common-lib:jar:1.2.1:compile
[INFO] |  +- com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter:jar:5.4.0:compile (version managed from 5.2.4)
[INFO] |  |  +- com.netflix.graphql.dgs:graphql-dgs-spring-boot-oss-autoconfigure:jar:5.4.0:compile (version managed from 5.4.0)
[INFO] |  |  |  +- (com.netflix.graphql.dgs:graphql-dgs:jar:5.4.0:compile - version managed from 5.4.0; omitted for duplicate)
[INFO] |  |  |  +- com.netflix.graphql.dgs:graphql-dgs-spring-webmvc:jar:5.4.0:compile (version managed from 5.4.0)
[INFO] |  |  |  |  +- (com.netflix.graphql.dgs:graphql-error-types:jar:5.4.0:compile - version managed from 5.4.0; omitted for duplicate)
[INFO] |  |  |  |  +- (com.netflix.graphql.dgs:graphql-dgs:jar:5.4.0:compile - version managed from 5.4.0; omitted for duplicate)
[INFO] |  |  |  |  +- (org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.6.21:compile - version managed from 1.7.20; omitted for duplicate)
[INFO] |  |  |  |  +- (org.jetbrains.kotlin:kotlin-reflect:jar:1.6.21:runtime - version managed from 1.7.20; omitted for duplicate)
[INFO] |  |  |  |  +- (com.fasterxml.jackson.module:jackson-module-kotlin:jar:2.13.4:runtime - version managed from 2.13.4; omitted for duplicate)
[INFO] |  |  |  |  \- (org.springframework:spring-web:jar:5.3.24:runtime - version managed from 5.3.23; omitted for duplicate)
[INFO] |  |  |  +- (org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.6.21:compile - version managed from 1.7.20; omitted for duplicate)
[INFO] |  |  |  +- (org.springframework:spring-web:jar:5.3.24:runtime - version managed from 5.3.23; omitted for duplicate)
[INFO] |  |  |  +- (org.springframework.boot:spring-boot-starter:jar:2.7.6:runtime - version managed from 2.6.12; omitted for duplicate)
[INFO] |  |  |  \- (org.apache.commons:commons-lang3:jar:3.12.0:runtime - version managed from 3.12.0; omitted for duplicate)
[INFO] |  |  +- com.netflix.graphql.dgs:graphql-dgs-spring-webmvc-autoconfigure:jar:5.4.0:compile (version managed from 5.4.0)
[INFO] |  |  |  +- (com.netflix.graphql.dgs:graphql-dgs:jar:5.4.0:compile - version managed from 5.4.0; omitted for duplicate)
[INFO] |  |  |  +- (com.netflix.graphql.dgs:graphql-dgs-spring-webmvc:jar:5.4.0:compile - version managed from 5.4.0; omitted for duplicate)
[INFO] |  |  |  +- (org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.6.21:compile - version managed from 1.7.20; omitted for duplicate)
[INFO] |  |  |  +- (org.springframework.boot:spring-boot-starter:jar:2.7.6:runtime - version managed from 2.6.12; omitted for duplicate)
[INFO] |  |  |  +- (org.springframework:spring-webmvc:jar:5.3.24:runtime - version managed from 5.3.23; omitted for duplicate)
[INFO] |  |  |  +- (jakarta.servlet:jakarta.servlet-api:jar:4.0.4:runtime - version managed from 4.0.4; omitted for duplicate)
[INFO] |  |  |  \- (com.fasterxml.jackson.module:jackson-module-kotlin:jar:2.13.4:runtime - version managed from 2.13.4; omitted for duplicate)
[INFO] |  |  +- com.netflix.graphql.dgs:graphql-dgs-client:jar:5.4.0:compile (version managed from 5.4.0)
[INFO] |  |  |  +- (com.jayway.jsonpath:json-path:jar:2.7.0:compile - version managed from 2.7.0; omitted for duplicate)
[INFO] |  |  |  +- (io.projectreactor:reactor-core:jar:3.4.25:compile - version managed from 3.4.23; omitted for duplicate)
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.4:compile (version managed from 2.13.4)
[INFO] |  |  |  +- com.netflix.graphql.dgs:graphql-dgs-subscription-types:jar:5.4.0:compile (version managed from 5.4.0)
[INFO] |  |  |  |  +- (com.graphql-java:graphql-java:jar:18.3:compile - version managed from 19.2; omitted for duplicate)
[INFO] |  |  |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.13.4:compile - version managed from 2.13.4; omitted for duplicate)
[INFO] |  |  |  |  +- (org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.6.21:compile - version managed from 1.7.20; omitted for duplicate)
[INFO] |  |  |  |  \- (org.springframework:spring-websocket:jar:5.3.24:runtime - version managed from 5.3.23; omitted for duplicate)
[INFO] |  |  |  +- (org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.6.21:compile - version managed from 1.7.20; omitted for duplicate)
[INFO] |  |  |  +- (org.springframework:spring-webflux:jar:5.3.24:runtime - version managed from 5.3.23; omitted for duplicate)
[INFO] |  |  |  +- (org.springframework:spring-web:jar:5.3.24:runtime - version managed from 5.3.23; omitted for duplicate)
[INFO] |  |  |  +- (com.fasterxml.jackson.module:jackson-module-kotlin:jar:2.13.4:runtime - version managed from 2.13.4; omitted for duplicate)
[INFO] |  |  |  +- (com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.4:runtime - version managed from 2.13.4; omitted for duplicate)
[INFO] |  |  |  +- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.13.4:compile (version managed from 2.13.4; scope not updated to compile)
[INFO] |  |  |  |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.13.4:compile - version managed from 2.13.4; omitted for duplicate)
[INFO] |  |  |  |  \- (com.fasterxml.jackson.core:jackson-databind:jar:2.13.4:compile - version managed from 2.13.4; omitted for duplicate)
[INFO] |  |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.13.4:compile (version managed from 2.13.4; scope not updated to compile)
[INFO] |  |  |  |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.13.4:compile - version managed from 2.13.4; omitted for duplicate)
[INFO] |  |  |  |  \- (com.fasterxml.jackson.core:jackson-databind:jar:2.13.4:compile - version managed from 2.13.4; omitted for duplicate)
[INFO] |  |  |  \- (com.graphql-java:graphql-java:jar:18.3:runtime - version managed from 19.2; omitted for duplicate)
[INFO] |  |  +- com.netflix.graphql.dgs:graphql-error-types:jar:5.4.0:compile (version managed from 5.4.0)
[INFO] |  |  |  +- (com.graphql-java:graphql-java:jar:18.3:compile - version managed from 19.2; omitted for duplicate)
[INFO] |  |  |  \- (org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.6.21:compile - version managed from 1.7.20; omitted for duplicate)
[INFO] |  |  +- (org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.6.21:compile - version managed from 1.7.20; omitted for duplicate)
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-websocket:jar:2.7.6:runtime (version managed from 2.6.12)
[INFO] |  |  |  +- (org.springframework.boot:spring-boot-starter-web:jar:2.7.6:runtime - version managed from 2.7.6; omitted for duplicate)
[INFO] |  |  |  +- org.springframework:spring-messaging:jar:5.3.24:runtime (version managed from 5.3.24)
[INFO] |  |  |  |  +- (org.springframework:spring-beans:jar:5.3.24:runtime - version managed from 5.3.24; omitted for duplicate)
[INFO] |  |  |  |  \- (org.springframework:spring-core:jar:5.3.24:runtime - version managed from 5.3.24; omitted for duplicate)
[INFO] |  |  |  \- org.springframework:spring-websocket:jar:5.3.24:runtime (version managed from 5.3.24)
[INFO] |  |  |     +- (org.springframework:spring-context:jar:5.3.24:runtime - version managed from 5.3.24; omitted for duplicate)
[INFO] |  |  |     +- (org.springframework:spring-core:jar:5.3.24:runtime - version managed from 5.3.24; omitted for duplicate)
[INFO] |  |  |     \- (org.springframework:spring-web:jar:5.3.24:runtime - version managed from 5.3.24; omitted for duplicate)
[INFO] |  |  \- (org.springframework.boot:spring-boot-starter-web:jar:2.7.6:runtime - version managed from 2.6.12; omitted for duplicate)
[INFO] +- com.netflix.graphql.dgs:graphql-dgs-extended-scalars:jar:5.4.0:compile
[INFO] |  +- com.netflix.graphql.dgs:graphql-dgs:jar:5.4.0:compile (version managed from 5.4.0)
[INFO] |  |  +- (com.netflix.graphql.dgs:graphql-error-types:jar:5.4.0:compile - version managed from 5.4.0; omitted for duplicate)
[INFO] |  |  +- com.netflix.graphql.dgs:graphql-dgs-mocking:jar:5.4.0:compile (version managed from 5.4.0)
[INFO] |  |  |  +- (com.graphql-java:graphql-java:jar:18.3:compile - version managed from 19.2; omitted for duplicate)
[INFO] |  |  |  +- (org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.6.21:compile - version managed from 1.7.20; omitted for duplicate)
[INFO] |  |  |  +- net.datafaker:datafaker:jar:1.4.0:runtime
[INFO] |  |  |  |  \- (com.github.mifmif:generex:jar:1.0.2:runtime - omitted for duplicate)
[INFO] |  |  |  \- (org.slf4j:slf4j-api:jar:1.7.36:runtime - version managed from 1.7.36; omitted for duplicate)
[INFO] |  |  +- com.graphql-java:graphql-java:jar:18.3:compile (version managed from 19.2; scope not updated to compile)
[INFO] |  |  |  +- com.graphql-java:java-dataloader:jar:3.1.2:compile
[INFO] |  |  |  |  \- (org.slf4j:slf4j-api:jar:1.7.36:compile - version managed from 1.7.30; omitted for duplicate)
[INFO] |  |  +- com.apollographql.federation:federation-graphql-java-support:jar:2.1.0:runtime (version managed from 2.1.0)
[INFO] |  |  |  +- com.apollographql.federation:federation-graphql-java-support-api:jar:2.1.0:runtime
[INFO] |  |  |  +- (com.graphql-java:graphql-java:jar:18.3:runtime - version managed from 19.2; omitted for duplicate)
[INFO] |  |  |  +- (org.slf4j:slf4j-api:jar:1.7.36:runtime - version managed from 1.7.36; omitted for duplicate)
[INFO] |  |  |  \- com.google.protobuf:protobuf-java:jar:3.19.6:runtime (version managed from 3.21.7)
[INFO] ------------------------------------------------------------------
```

**Comment by sijonelis** [comment]
Still an issue in the 5.5.0 as well

**Comment by SquireOfSoftware** [comment]
Ok...so I think I got...something to work...but it involves a few things.

# Where am I coming in from?

I have this Kotlin project, it runs on JDK 17 with Spring Boot `2.7.3`, Spring Gradle dependency management 1.0.13.RELEASE etc. blah blah, here is my old gradle file:

<details>
<summary>My old gradle file</summary>

```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id("org.springframework.boot") version "2.7.3"
	id("io.spring.dependency-management") version "1.0.13.RELEASE"
	kotlin("jvm") version "1.6.21"
	kotlin("plugin.spring") version "1.6.21"
}

group = "com.squireofsoftware"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_17

repositories {
	mavenCentral()
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter-web")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	testImplementation("org.springframework.boot:spring-boot-starter-test")

	implementation(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:latest.release"))
	implementation("com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter")
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs = listOf("-Xjsr305=strict")
		jvmTarget = "17"
	}
}

tasks.withType<Test> {
	useJUnitPlatform()
}
```
</details>

Now as far as I know, the last time I built this project was with DGS `5.3.0`, I believe as of writing this, it is on `6.0.0`?

I did try hard coding the version from 5.4.0 and it starts failing, which is:

```
	implementation(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:5.4.0"))
```

Citing errors like:
<details>
<summary>Start up error</summary>

```
The called method's class hierarchy was loaded from the following locations:

    graphql.schema.idl.RuntimeWiring: file:/~/.gradle/caches/modules-2/files-2.1/com.graphql-java/graphql-java/18.3/d30b46b4db4818fc6547d233b7aef5af6dcfe715/graphql-java-18.3.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes com.apollographql.federation.graphqljava.Federation and graphql.schema.idl.RuntimeWiring
```
</details>

So the failure appears to be somewhere between 5.3.0 and 5.4.0? Which is this change: https://github.com/Netflix/dgs-framework/releases/tag/v5.4.0

I then upgraded to `6.0.0` and I get a different error which is:

<details>
<summary>Spring Boot logs</summary>

```
...
o.apache.catalina.core.StandardService   : Starting service [Tomcat]
org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.65]
o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 527 ms
ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.netflix.graphql.dgs.webmvc.autoconfigure.GraphiQLConfigurer': Resolution of declared constructors on bean Class [com.netflix.graphql.dgs.webmvc.autoconfigure.GraphiQLConfigurer] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@251a69d7] failed; nested exception is java.lang.NoClassDefFoundError: jakarta/servlet/ServletContext
...
```
</details>

So then I started playing around and I think I got something to work?

# Cut to the chase old man, what did you end up with in your `build.gradle.kts`?

<details>
<summary>Resulting Gradle file</summary>

```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id("org.springframework.boot") version "3.0.0" // take note that I did have to upgrade this
	id("io.spring.dependency-management") version "1.0.14.RELEASE" // I also upgraded this as well
	kotlin("jvm") version "1.6.21"
	kotlin("plugin.spring") version "1.6.21"
}

group = "com.squireofsoftware"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_17

repositories {
	mavenCentral()
}

// I added this block in as per the example here: https://netflix.github.io/dgs/advanced/platform-bom/#using-the-platformbom
dependencyManagement {
	imports {
		mavenBom("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:latest.release")
	}
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter-web")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	testImplementation("org.springframework.boot:spring-boot-starter-test")

// according to this PR: https://github.com/Netflix/dgs-examples-java/pull/102/files 
// you are not supposed to have this import any more? the BOM should sort it out apparently
//	implementation(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:latest.release"))
	implementation("com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter")
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs = listOf("-Xjsr305=strict")
		jvmTarget = "17"
	}
}

tasks.withType<Test> {
	useJUnitPlatform()
}
```

</details>

So I did a few things:
1. I commented out the `implementation(platform(...` line in my `dependencies` block 
**Take note code still failed at this point**
2. I then added in the `dependencyManagement` block as suggested by the updated documentation: https://netflix.github.io/dgs/advanced/platform-bom/#using-the-platformbom
**Take note code still failed to start up at this point**
3. I then upgraded my spring dependency plugin to `1.0.14.RELEASE`
**Take note code still failed to start up at this point**
4. I then added in the `extra[java...` syntax
**Take note code still failed to start up at this point**
5. I then bumped up the spring dependency version to `1.0.14.RELEASE`
**Take note code still failed to start up at this point**
6. I then bumped up the spring version to `3.0.0` (since I was also on JDK 17)
**CODE FINALLY STARTED UP**
7. I then REMOVED the `extra[java...` syntax
**Code continued to start up**
8. I then downgraded the spring dependency plugin back down to `1.0.13.RELEASE`
**Code continued to start up** 
9. I then downgraded the version of Spring Boot to `2.7.8`
**Take note that code failed to start up**
10. I then removed the `dependencyManagement` block
**Code failed to compile**

I wonder if there is a hard requirement on DGS relying on Spring Boot `2.x` to `3.x` that the bom plugin relies on?

I guess this is what this part of the intro page meant:
![image](https://user-images.githubusercontent.com/8869415/214709601-e1efd7e5-d15a-403d-9ca2-aa2409611771.png)

Though it is misleading as the following sentence says: `Note that you can still use the DGS framework with Spring Boot 2.7 by using a 5.x release.` In my case, I could only go up to `5.3.0` as `5.4.0` ended up erroring out on me.

And it also seems like the `extra[java...` syntax did nothing to sort out the runtime issue in my project. But maybe I misunderstood how this was meant to be used?

I haven't yet experimented with JDK 11, I imagine that has a whole other side of compatibility issues, given that Spring Boot `3.x` relies on JDK 17 now: https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0

But maybe this is a good thing? Maybe it forces old projects to upgrade to Spring Boot `3.0.0`?

**Comment by srinivasankavitha** [comment]
Apologies for the confusion, I will add some more clarification in the DGS
docs, but here are the compatible versions:

1) DGS 6.0.0 relies on Spring Boot 3.0 and JDK 17
2) DGS 5.5.x relies on Spring Boot 2.7 and should work with JDK 8. 11 and 17
3) DGS <5.4.x relies on Spring Boot 2.6

Hope that helps.

**Comment by SquireOfSoftware** [comment]
> 2) DGS 5.5.x relies on Spring Boot 2.7 and should work with JDK 8. 11 and 17

@srinivasankavitha Oh interesting! My project was Spring Boot `2.7.3`, JDK 17 and it seemed only DGS `5.3.0` worked for it, anything higher seemed to fail

**Comment by srinivasankavitha** [comment]
We have a working example of Spring Boot 2.7 with DGS 5.5.1 here:
https://github.com/Netflix/dgs-examples-java-2.7

**Comment by SquireOfSoftware** [comment]
Ah interesting! Spring Boot 2.7 with DGS 5.5.1 with JDK 8 and Gradle 7.2.

It is interesting that it works without the `mavenBom` codeblock in place (I tinkered with both JDK 17 and JDK 8 on the example project and both compiled and ran fine).

Interesting so this fails for me:

Which is Spring Boot `2.7.3`, no `dependencyManagement` block, hard coded DGS `5.5.1`, JDK 17 and gradle 7.5.

Downgrading my project down to JDK 8, makes the `build.gradle.kts` file unrecognisable.

I wonder if gradle is the variation here...

Anyways the error that is cited as I run the application is:

```
The called method's class hierarchy was loaded from the following locations:

    graphql.schema.idl.RuntimeWiring: file:/~/.gradle/caches/modules-2/files-2.1/com.graphql-java/graphql-java/18.3/d30b46b4db4818fc6547d233b7aef5af6dcfe715/graphql-java-18.3.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes com.apollographql.federation.graphqljava.Federation and graphql.schema.idl.RuntimeWiring
```

Seems like its routing to graphql-java-18.3 instead of the suggested 19.2. It would imply that the compatibility between DGS 5.3 and 5.3+ are a little bit more nuance that first meets the eye as the only variation then between my setup and the example is the JDK versions (but as proven at the top, JDK is not a factor here) and the gradle version.

But my setup anyways seems to scream: `just use the latest Spring Boot and the latest LTS JDK` (as noted with gradle 7.5) and because I am not even going to bother with testing out the many permutations of gradle compatibility with JDK and spring boot AND DGS...so I am gonna let this rest. 

I guess the moral of the story is, upgrade to Spring Boot 3.x, JDK 17, gradle 7.2+ and you should be able to avoid most of these compatibility problems.

**Comment by david-newspark** [comment]
In maven you need to order the dependency mgmt with DGS above Spring boot:

```
  <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.netflix.graphql.dgs</groupId>
                <artifactId>graphql-dgs-platform-dependencies</artifactId>
                <!-- The DGS BOM/platform dependency. This is the only place you set version of DGS -->
                <version>5.5.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

This appears to be working...2.7.8 & 5.5.1

**Comment by noorul** [comment]
This work around helps, Thank you @david-newspark

**Comment by pdsway** [comment]
Hi...

  In my maven SB 2.7 project I cannot control the bom order (I get Spring from parent) but adding this property will override the graphql-java version for maven users...
```
    <properties>
        <graphql-java.version>19.2</graphql-java.version>
    </properties>
```
