### ISSUE TITLE
bug: Handler dispatch failed: java.lang.NoClassDefFoundError: Could not initialize class com.netflix.graphql.dgs.DgsExecutionResult$Builder with Spring Boot + Kotlin + Maven

### ISSUE THREAD

**Issue by vladkanash** [Netflix/dgs-framework#1576]
/graphql endpoint returns 500 for every request, logs show `NoClassDefFoundError`
Can be reproduced with the example from DGS [getting started guide](https://netflix.github.io/dgs/getting-started/)

```
2023-07-06T14:58:15.401+02:00 ERROR 27726 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.NoClassDefFoundError: Could not initialize class com.netflix.graphql.dgs.DgsExecutionResult$Builder] with root cause

java.lang.NoClassDefFoundError: Could not initialize class com.netflix.graphql.dgs.DgsExecutionResult$Builder
	at com.netflix.graphql.dgs.DgsExecutionResult$Companion.builder(DgsExecutionResult.kt:137) ~[graphql-dgs-7.2.0.jar:7.2.0]
	at com.netflix.graphql.dgs.mvc.DgsRestController.executeQuery(DgsRestController.kt:236) ~[graphql-dgs-spring-webmvc-7.2.0.jar:7.2.0]
	at com.netflix.graphql.dgs.mvc.DgsRestController.graphql(DgsRestController.kt:132) ~[graphql-dgs-spring-webmvc-7.2.0.jar:7.2.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-6.0.10.jar:6.0.10]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-web-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[tomcat-embed-core-10.1.10.jar:6.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.10.jar:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.10.jar:10.1.10]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.10.jar:6.0.10]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.10.jar:6.0.10]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.0.10.jar:6.0.10]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.10.jar:6.0.10]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.10.jar:6.0.10]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.10.jar:6.0.10]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```
## Dependencies versions:
Spring Boot: 3.0.8
DGS: 7.2.0
Kotlin: 1.8.21

## Steps to reproduce
A reproducible example can be found here: 
https://github.com/vladkanash/dgs-demo

Run the app and try to perform any query through graphiql UI, I.E.
```
{
  shows {
    title
  }
}
```

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by srinivasankavitha** [comment]
We generally use gradle and do't actively support maven projects. I would suggest you try out one of our existing kotlin samples here for reference: https://github.com/Netflix/dgs-examples-kotlin

**Comment by vladkanash** [comment]
I can reproduce the same exact issue when using gradle.
See https://github.com/vladkanash/dgs-demo-gradle

**Comment by fmignone-appdirect** [comment]
Hi everyone! I have the same problem! I have a gradle project, and all my pods are crashing with the same error, which is strange because the class `DgsRestController`, which is the one that calls the builder, is in the same package. Building the application is no problem, but it throws this error in runtime. My project has the following versions:
- Java: 17
- Gradle: 7.6.1
-Netflix Graphql Dgs Version = 6.0.5

I really appreciate any help you can provide!

**Comment by congotej** [comment]
Hi @vladkanash @fmignone-appdirect! Thank you for bringing this to our attention. We will look into it and provide more info shortly.

**Comment by vladkanash** [comment]
After some investigation I found out that the reason for the issue is that this particular version of spring boot has a dependency on a different version of `graphql-java`, not the one that DGS is using. 
I was able to fix it in maven project by specifying the correct version in `dependencyManagement` section:
```
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.graphql-java</groupId>
      <artifactId>graphql-java</artifactId>
      <version>20.3</version>
    </dependency>
  </dependencies>
</dependencyManagement>
```

**Comment by fmignone-appdirect** [comment]
Hi everyone! My solution was to upgrade the following dependencies using the `7.2.0` version:

```
implementation(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:${netflixGraphqlDgsVersion}"))
implementation "com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter:${netflixGraphqlDgsVersion}"
```

By the way, the versions that I'm currently using are:
- Java: 17
- Gradle: 7.6.1
- Netflix Graphql Dgs Version: 7.2.0 (solved the issue)
- Spring Boot: 3.1.1

**Comment by congotej** [comment]
@vladkanash 
> the issue is that this particular version of spring boot has a dependency on a different version of graphql-java, not the one that DGS is using.

We are currently on graphql-java 20.3 since [v7.2.0](https://github.com/Netflix/dgs-framework/releases/tag/v7.2.0). I see from the initial comment that you are on `DGS: version 7.2.0` so your project should already be using graphql-java 20.3.
However as Kavitha mentioned we don't actively support maven projects so there could be some underlying reason why that graphql-java version is not being picked up unless manually set. 

Regardless, I am glad you were able to resolve the issue by specifying the correct version. Would it be ok if I close out this ticket, or is there anything pending that I can help you with?

**Comment by congotej** [comment]
Going to go ahead and close this out since the issue appears to be resolved!
