### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by mr-nothing** [Netflix/dgs-framework#1593]
Unable to get partial results while fetching entities via DGS federation. 

## Expected behavior

Both errors and data are returned based on the entities fetched by DGS federation:
```
{
  "errors": [
    {
      "message": "Child with id 12345 not found",
      "extensions": {
        "code": "DOWNSTREAM_SERVICE_ERROR",
        "serviceName": "child_service",
        "errorType": "INTERNAL",
        "exception": {
          "message": "Child with id 12345 not found",
          "locations": [],
          "path": [
            "_entities"
          ],
          "stacktrace": [
            "GraphQLError: Child with id 12345 not found",
            "    at downstreamServiceError (/dev/apollo-gateway/node_modules/@apollo/gateway/src/executeQueryPlan.ts:633:10)",
            "    at /dev/apollo-gateway/node_modules/@apollo/gateway/src/executeQueryPlan.ts:448:9",
            "    at Array.map (<anonymous>)",
            "    at sendOperation (/dev/apollo-gateway/node_modules/@apollo/gateway/src/executeQueryPlan.ts:447:38)",
            "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
            "    at async /dev/apollo-gateway/node_modules/@apollo/gateway/src/executeQueryPlan.ts:360:41",
            "    at async executeNode (/dev/apollo-gateway/node_modules/@apollo/gateway/src/executeQueryPlan.ts:243:9)",
            "    at async executeNode (/dev/apollo-gateway/node_modules/@apollo/gateway/src/executeQueryPlan.ts:223:17)",
            "    at async executeNode (/dev/apollo-gateway/node_modules/@apollo/gateway/src/executeQueryPlan.ts:191:32)",
            "    at async /dev/apollo-gateway/node_modules/@apollo/gateway/src/executeQueryPlan.ts:76:27"
          ]
        }
      }
    },
    // More errors go here...
  ],
  "data": {
     "getParents": [
            {
                "id": 45,
                "children": [
                    {
                        "child": {
                            "id": "70207"
                            "name": "child-name"
                        }
             },
     ]
  }
}
```

## Actual behavior

`data: null` along with bunch of errors are returned:
```
{
  "errors": [
    {
      "message": "Child with id 12345 not found",
      "extensions": {
        "code": "DOWNSTREAM_SERVICE_ERROR",
        "serviceName": "child_service",
        "errorType": "INTERNAL",
        "exception": {
          "message": "Child with id 12345 not found",
          "locations": [],
          "path": [
            "_entities"
          ],
          "stacktrace": [
            "GraphQLError: Child with id 12345 not found",
            "    at downstreamServiceError (/dev/apollo-gateway/node_modules/@apollo/gateway/src/executeQueryPlan.ts:633:10)",
            "    at /dev/apollo-gateway/node_modules/@apollo/gateway/src/executeQueryPlan.ts:448:9",
            "    at Array.map (<anonymous>)",
            "    at sendOperation (/dev/apollo-gateway/node_modules/@apollo/gateway/src/executeQueryPlan.ts:447:38)",
            "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
            "    at async /dev/apollo-gateway/node_modules/@apollo/gateway/src/executeQueryPlan.ts:360:41",
            "    at async executeNode (/dev/apollo-gateway/node_modules/@apollo/gateway/src/executeQueryPlan.ts:243:9)",
            "    at async executeNode (/dev/apollo-gateway/node_modules/@apollo/gateway/src/executeQueryPlan.ts:223:17)",
            "    at async executeNode (/dev/apollo-gateway/node_modules/@apollo/gateway/src/executeQueryPlan.ts:191:32)",
            "    at async /dev/apollo-gateway/node_modules/@apollo/gateway/src/executeQueryPlan.ts:76:27"
          ]
        }
      }
    },
    // More errors go here...
  ],
  "data": null
}
```

## Steps to reproduce

1.  Have the following schema definitions on parent service side:
```
type Parent @key(fields: "id") {
    id: Long!
    children: [Child!]!
}
type ChildRelation @key(fields: "id") {
    id: String!
    child: Child!
}
type Child @key(fields: "id") @extends{
    id: String! @external
}
```

2. Have the following schema definitions on child service side:
```
type Child @key(fields: "id") {
    id: String!
    name: String!
}
``` 

3. Have the following components defined in child service:
entity fetcher:
```
@DgsComponent
class ChildEntityFetcher {
    @DgsEntityFetcher
    fun childEntityFetcher(
        values: Map<Any, Any>,
        dfe: DgsDataFetchingEnvironment
    ): CompletableFuture<Child> {
        val childId: String = values["id"].toString()
        val loader: DataLoader<String, Child> = dfe.getDataLoader(ChildDataLoader::class.java)
        return loader.load(childId)
    }
}
```
Data loader:
```
@DgsDataLoader
class ChildDataLoader(
    private val myParentService: MyParentService
) : MappedBatchLoader<String, Try<ParentData>> {

    override fun load(keys: MutableSet<String>): CompletionStage<Map<String, Try<ParentData>>> {

        return CompletableFuture.supplyAsync {
            val results = myParentService.getParentDataByIds(keys)
                .associate { it.id to Try.succeeded(it) }
                .toMutableMap<String, Try<MyParentData>>()
            for (key in keys) {
                results.putIfAbsent(key, Try.failed(DgsEntityNotFoundException("Child with id $key not found")))
            }
            results
        }
    }
}
```
As far as I understand the fact that I return `Try` wrapper instead of data should make it possible to do a partial loading though it seems this is not the case.

4. Make any request to parent service to fetch parent with its children, for example:
```
query getAllParents {
    getAllParents {
        id
        children {
            id
            child {
                id
                name
            }
        }
    }
}
```

5. Make sure `data` and `errors` blocks are filled in the response.

**Comment by mr-nothing** [comment]
I upgraded some DGS dependencies and this seems to be working now, thank you!
