### ISSUE TITLE
bug:  Mock Provider - Union

### ISSUE THREAD

**Issue by Sreddy89** [Netflix/dgs-framework#1634]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior
Application should start without exception

## Actual behavior
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dgsQueryExecutor' defined in class path resource [com/netflix/graphql/dgs/autoconfig/DgsAutoConfiguration.class]: Unsatisfied dependency expressed through method 'dgsQueryExecutor' parameter 1: Error creating bean with name 'schema' defined in class path resource [com/netflix/graphql/dgs/autoconfig/DgsAutoConfiguration.class]: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'schema' threw exception with message: class graphql.schema.GraphQLInterfaceType cannot be cast to class graphql.schema.GraphQLObjectType (graphql.schema.GraphQLInterfaceType and graphql.schema.GraphQLObjectType are in unnamed module of loader 'app')
                at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
                at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:550)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
                at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
                at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
                at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
                at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
                at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
                at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
                at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436)
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'schema' defined in class path resource [com/netflix/graphql/dgs/autoconfig/DgsAutoConfiguration.class]: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'schema' threw exception with message: class graphql.schema.GraphQLInterfaceType cannot be cast to class graphql.schema.GraphQLObjectType (graphql.schema.GraphQLInterfaceType and graphql.schema.GraphQLObjectType are in unnamed module of loader 'app')
                at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659)
                at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:647)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
                at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
                at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
                at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
                at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
                at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:888)
                at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
                ... 19 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'schema' threw exception with message: class graphql.schema.GraphQLInterfaceType cannot be cast to class graphql.schema.GraphQLObjectType (graphql.schema.GraphQLInterfaceType and graphql.schema.GraphQLObjectType are in unnamed module of loader 'app')
                at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
                at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655)
                ... 33 more
Caused by: java.lang.ClassCastException: class graphql.schema.GraphQLInterfaceType cannot be cast to class graphql.schema.GraphQLObjectType (graphql.schema.GraphQLInterfaceType and graphql.schema.GraphQLObjectType are in unnamed module of loader 'app')
                at com.netflix.graphql.mocking.MockGraphQLVisitor.visitGraphQLFieldDefinition(MockGraphQLVisitor.kt:62)
                at graphql.schema.GraphQLFieldDefinition.accept(GraphQLFieldDefinition.java:201)
                at graphql.schema.SchemaTraverser$TraverserDelegateVisitor.enter(SchemaTraverser.java:109)
                at graphql.util.Traverser.traverse(Traverser.java:144)
                at graphql.schema.SchemaTraverser.doTraverse(SchemaTraverser.java:96)
                at graphql.schema.SchemaTraverser.depthFirst(SchemaTraverser.java:86)
                at graphql.schema.SchemaTraverser.depthFirst(SchemaTraverser.java:79)
                at graphql.schema.SchemaTraverser.depthFirst(SchemaTraverser.java:75)
                at com.netflix.graphql.mocking.DgsSchemaTransformer.transformSchema(DgsSchemaTransformer.kt:35)
                at com.netflix.graphql.mocking.DgsSchemaTransformer.transformSchemaWithMockProviders(DgsSchemaTransformer.kt:29)
                at com.netflix.graphql.dgs.internal.DgsSchemaProvider.computeSchema(DgsSchemaProvider.kt:210)
                at com.netflix.graphql.dgs.internal.DgsSchemaProvider.schema(DgsSchemaProvider.kt:132)
                at com.netflix.graphql.dgs.autoconfig.DgsAutoConfiguration.schema(DgsAutoConfiguration.kt:219)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:568)
                at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)

## Steps to reproduce

Schema: 
type Person {
    id: ID
    name: Name
    salary: Float
    married: Boolean
    address: Address
}

type Name {
    firstname: String
    middleName: String
    lastName: String
}

type Address {
    houseNumber: Int
    street: String
    state: String
    country: String
}

type Query {
    person(name: String): PersonResult
}
interface Error {
    code: String!
    reason: String
    message: String
}

type PersonError implements Error {
    code: String!
    reason: String
    message: String
}

union PersonResult = Person  | PersonError

Mock Java class:

@Component

public class PersonDataProvider implements MockProvider {

    @Override
    public Map<String, Object> provide() {
        var map = new HashMap<String, Object>();
        map.put("person",null);
        return map;
    }

}

Additional info:

Spring boot Parent - spring-boot-starter-parent - 3.1.0
graphql-dgs-platform-dependencies - 7.3.3
Java 17

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by congotej** [comment]
Hi @Sreddy89 ! The error message you shared indicates an issue related to GraphQL schema generation and type casting. I tried to reproduce the error with the schema you provided, but it successfully booted up for me. I would recommend reviewing your mock provider (PersonDataProvider) and verify that it returns data that matches the schema. Double-check that the data structure for the person field aligns with the expected type structure. 
If you have specific code snippets or more details about your GraphQL setup, please provide them and I can try to help pinpoint the problem, as I was not able to reproduce with the info you provided.
