### ISSUE TITLE
bug: MissingParametersCompilerArgumentException while trying to build native Spring Boot

### ISSUE THREAD

**Issue by brianpreuss** [Netflix/dgs-framework#1640]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior

Native image compilating with Spring Boot 3.1.3, Gradle 8.3 and Netflix DGS 7.5.1 should work without any exceptions.

## Actual behavior
AOT-Processing of Spring Boot Grade Plugins fails with a MissingParametersCompilerArgumentException.

`Exception in thread "main" org.springframework.boot.context.properties.bind.MissingParametersCompilerArgumentException: Constructor binding in a native image requires compilation with -parameters but the following classes were compiled without it:
        com.netflix.graphql.dgs.metrics.micrometer.DgsGraphQLMetricsProperties$CardinalityLimiterKind

        at org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar.registerHints(BindableRuntimeHintsRegistrar.java:100)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBeanFactoryInitializationAotProcessor$ConfigurationPropertiesReflectionHintsContribution.applyTo(ConfigurationPropertiesBeanFactoryInitializationAotProcessor.java:74)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.applyTo(BeanFactoryInitializationAotContributions.java:78)
        at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
        at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
        at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
        at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
        at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
        at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)`

## Steps to reproduce

Create a Spring Boot 3.1.3 Gradle (8.3) project, use Netflix DGS with com.netflix.graphql.dgs:graphql-dgs-webflux-starter version 7.5.1

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by kilink** [comment]
That particular exception is strange, since CardinalityLimiterKind is an enum; but regardless, this project doesn't currently support AOT, and would likely require many other changes / fixes to do so. Resolving this issue for now since AOT is not currently in scope.
