### ISSUE TITLE
ClassNotFoundException: graphql.execution.instrumentation.SimplePerformantInstrumentation

### ISSUE THREAD

**Issue by emeraldhieu** [Netflix/dgs-framework#1672]
## Expected behavior

Spring Boot starts successfully.

## Actual behavior

```
Caused by: java.lang.NoClassDefFoundError: graphql/execution/instrumentation/SimplePerformantInstrumentation
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[na:na]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3502) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2601) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465) ~[spring-core-6.0.2.jar:6.0.2]
	... 21 common frames omitted
```

[errorLogs.txt](https://github.com/Netflix/dgs-framework/files/12920674/errorLogs.txt)

## Steps to reproduce

Start this `OrderApp`.

https://github.com/emeraldhieu/issue-reproduction/tree/master

---

I've tried [this](https://stackoverflow.com/questions/58421858/java-lang-noclassdeffounderror-graphql-execution-instrumentation-simpleinstrume#58424293) but I see there's only one `graphql-java:19.2`

```
[INFO] \- com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter:jar:7.6.0:compile
[INFO]    +- com.netflix.graphql.dgs:graphql-dgs-spring-boot-oss-autoconfigure:jar:7.6.0:compile
[INFO]    |  +- com.netflix.graphql.dgs:graphql-dgs:jar:7.6.0:compile
[INFO]    |  |  +- com.netflix.graphql.dgs:graphql-dgs-mocking:jar:7.6.0:compile
[INFO]    |  |  |  \- net.datafaker:datafaker:jar:1.9.0:runtime
[INFO]    |  |  |     \- com.github.mifmif:generex:jar:1.0.2:runtime
[INFO]    |  |  |        \- dk.brics.automaton:automaton:jar:1.11-8:runtime
[INFO]    |  |  +- org.jetbrains.kotlin:kotlin-reflect:jar:1.7.21:runtime
[INFO]    |  |  +- com.apollographql.federation:federation-graphql-java-support:jar:3.0.0:runtime
[INFO]    |  |  |  +- com.apollographql.federation:federation-graphql-java-support-api:jar:3.0.0:runtime
[INFO]    |  |  |  \- com.google.protobuf:protobuf-java:jar:3.22.1:runtime
[INFO]    |  |  +- org.jetbrains.kotlinx:kotlinx-coroutines-core:jar:1.6.4:runtime
[INFO]    |  |  |  \- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:jar:1.6.4:runtime
[INFO]    |  |  +- org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:jar:1.6.4:runtime
[INFO]    |  |  \- org.jetbrains.kotlinx:kotlinx-coroutines-reactor:jar:1.6.4:runtime
[INFO]    |  |     \- org.jetbrains.kotlinx:kotlinx-coroutines-reactive:jar:1.6.4:runtime
[INFO]    |  +- com.netflix.graphql.dgs:graphql-dgs-spring-webmvc:jar:7.6.0:compile
[INFO]    |  \- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO]    +- com.netflix.graphql.dgs:graphql-dgs-spring-webmvc-autoconfigure:jar:7.6.0:compile
[INFO]    |  +- jakarta.servlet:jakarta.servlet-api:jar:6.0.0:runtime
[INFO]    |  \- com.fasterxml.jackson.module:jackson-module-kotlin:jar:2.14.1:runtime
[INFO]    +- com.netflix.graphql.dgs:graphql-dgs-client:jar:7.6.0:compile
[INFO]    |  +- com.jayway.jsonpath:json-path:jar:2.7.0:compile
[INFO]    |  |  \- net.minidev:json-smart:jar:2.4.8:compile
[INFO]    |  |     \- net.minidev:accessors-smart:jar:2.4.8:compile
[INFO]    |  |        \- org.ow2.asm:asm:jar:9.1:compile
[INFO]    |  +- io.projectreactor:reactor-core:jar:3.5.0:compile
[INFO]    |  |  \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.14.1:compile
[INFO]    |  +- com.netflix.graphql.dgs:graphql-dgs-subscription-types:jar:7.6.0:compile
[INFO]    |  +- com.graphql-java:graphql-java:jar:19.2:compile
[INFO]    |  |  \- com.graphql-java:java-dataloader:jar:3.2.0:compile
[INFO]    |  \- org.jetbrains:annotations:jar:13.0:compile
[INFO]    +- com.netflix.graphql.dgs:graphql-error-types:jar:7.6.0:compile
[INFO]    +- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.7.21:compile
[INFO]    |  +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.7.21:compile
[INFO]    |  |  \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.7.21:compile
[INFO]    |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.7.21:compile
[INFO]    \- org.springframework.boot:spring-boot-starter-websocket:jar:3.0.0:runtime
[INFO]       +- org.springframework:spring-messaging:jar:6.0.2:runtime
[INFO]       \- org.springframework:spring-websocket:jar:6.0.2:runtime
```

**Comment by srinivasankavitha** [comment]
We generally support gradle but maven is not officially supported by us. It sounds like you are running into dependency conflicts due to conflicts with graphql-java but the version looks incorrect for `7.6.0`. It should be using  graphql-java`20.6`. Could you try pinning to that in your maven project?
```
<properties>
    <graphql-java.version>20.6</graphql-java.version>
</properties>
```

**Comment by emeraldhieu** [comment]
Thanks but it doesn't work. I also tried adding

```
<dependency>
    <groupId>com.graphql-java</groupId>
    <artifactId>graphql-java</artifactId>
    <version>21.2</version>
</dependency>
```

but it still fails with that error.

**Comment by kilink** [comment]
This seems like a Maven / Spring Boot configuration issue, since the configured graphql-java version is not getting picked up in your pom.xml; you might also consider updating to Spring Boot 3.2.x and DGS 8.x, which does seem to result in the newer graphql-java version being pulled in.
