### ISSUE TITLE
bug: Error when fetching schemas from server

### ISSUE THREAD

**Issue by yesjinu** [Netflix/dgs-framework#1687]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior

- Fetching schemas succeeds after building application.

## Actual behavior

- It throws `ServletException` when I tried to fetch schemas.

```
jakarta.servlet.ServletException: Handler dispatch failed: java.lang.NoSuchFieldError: DISPATCH_NEVER
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1096)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
        ...
Caused by: java.lang.NoSuchFieldError: DISPATCH_NEVER
	at com.netflix.graphql.dgs.internal.DgsDataLoaderProvider.buildRegistryWithContextSupplier(DgsDataLoaderProvider.kt:66)
	at com.netflix.graphql.dgs.internal.BaseDgsQueryExecutor.baseExecute(BaseDgsQueryExecutor.kt:107)
	at com.netflix.graphql.dgs.internal.DefaultDgsQueryExecutor.execute(DefaultDgsQueryExecutor.kt:84)
	at com.netflix.graphql.dgs.mvc.DgsRestController$executeQuery$executionResult$1.invoke(DgsRestController.kt:215)
	at com.netflix.graphql.dgs.mvc.DgsRestController$executeQuery$executionResult$1.invoke(DgsRestController.kt:213)
	at com.netflix.graphql.dgs.internal.utils.TimeTracer.logTime(TimeTracer.kt:24)
	at com.netflix.graphql.dgs.mvc.DgsRestController.executeQuery(DgsRestController.kt:213)
	at com.netflix.graphql.dgs.mvc.DgsRestController.graphql(DgsRestController.kt:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
```

## Steps to reproduce

I had these dependencies in my `build.gradle.kts`. It breaks when trying to fetch schemas from server. 

```yml
dependencies {
    ...
    implementation(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:latest.release"))
    implementation("com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter:7.6.0")
    ...
}

```

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by yesjinu** [comment]
I fixed the issue by specify the version of `graphql-dgs-platform-dependencies` from `latest.release` to `7.6.0`.

```yml
dependencies {
    ...
    implementation(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:7.6.0"))
    implementation("com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter:7.6.0")
    ...
}
```

**Comment by srinivasankavitha** [comment]
Thanks for the update. I will close this issue in that case.

**Comment by bomber-lomber** [comment]
Hey @srinivasankavitha I have the same bug and get it with `build.gradle.kts` dependencies:
```
dependencies {
    ...
    implementation(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:8.0.0"))
    implementation("com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter")
    ...
}
```

**Comment by hwhh** [comment]
Yeah seeing this too, since upgrading from 7.6.0 to 8

**Comment by srinivasankavitha** [comment]
Are you folks by any chance using the spring dependency management plugin? 
```
plugins {
     id 'io.spring.dependency-management' version '1.1.3'
}
```

This brings in graphql-java 20.2, which is conflicting with what we are now using the DGS framework 8.0.0 which is 21.2. I suspect this is causing issues with the version of java-dataloader dependency that is brought in. Is it possible to try without it or explicitly specifying the graphql-java version to be 21.2 to override what the dependency management plugin is using?

https://docs.spring.io/spring-boot/docs/3.1.1/reference/html/dependency-versions.html#appendix.dependency-versions

**Comment by bthreader** [comment]
> Are you folks by any chance using the [spring dependency management plugin](https://docs.spring.io/spring-boot/docs/3.1.1/reference/html/dependency-versions.html#appendix.dependency-versions)?
> 
> ```
> plugins {
>      id 'io.spring.dependency-management' version '1.1.3'
> }
> ```

Yes, with this exact version. Spring Initializr includes this by default.

> 1. explicitly specifying the graphql-java version to be 21.2 to override what the dependency management plugin is using

This worked for me, thanks 😄

Here's the Gradle dependency incase anyone wants a quick copy paste:

```
dependencies {
    ...
    implementation 'com.graphql-java:graphql-java:21.2'
    ...
}
```

**Comment by sbarroso-RatedPower** [comment]
Hi there!

I'm having same issue but it didn't works for me. I got this warnings and the GraphQL endpoint returns 404:

```
17:10:39.010 [main] WARN  o.s.c.a.AnnotationTypeMapping - Support for convention-based annotation attribute overrides is deprecated and will be removed in Spring Framework 6.2. Please annotate the following attributes in @com.netflix.graphql.dgs.DgsMutation with appropriate @AliasFor declarations: [field] 
```
```
17:10:39.010 [main] WARN  o.s.c.a.AnnotationTypeMapping - Support for convention-based annotation attribute overrides is deprecated and will be removed in Spring Framework 6.2. Please annotate the following attributes in @com.netflix.graphql.dgs.DgsQuery with appropriate @AliasFor declarations: [field]
```

this is my config:

```
dependencyManagement {
    imports {
        mavenBom "com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:${queryDslVersion}"
    }
}

implementation 'com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter'
implementation 'com.netflix.graphql.dgs:graphql-dgs-extended-scalars'
```

Did some one know how to fix it?

**Comment by sbarroso-RatedPower** [comment]
> Hey Samuel, try to use
> 
> ```
>     implementation("com.graphql-java:graphql-java:21.2")
>     implementation(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:8.0.0"))
> ```
> 
> instead of
> 
> ```
> dependencyManagement {
>     imports {
>         mavenBom "com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:8.0.1"
>     }
> }
> ```

It is working! Thank you so much 😄
