### ISSUE TITLE
bug: Incompatibility between DGS 10.0.1 and Spring-GraphQL’s SchemaMappingInspector in Mvc-Tests

### ISSUE THREAD

**Issue by colomdan** [Netflix/dgs-framework#2097]
In DGS **10.0.1**, we are now running tests with `@EnableDgsMockMvcTest`.
In these tests, DGS validates our schema using the `SchemaMappingInspector` from spring-graphql.
This inspector does not allow the same patterns for Java Beans as DGS does. Boolean flags cannot be resolved the following way.

`allowed: Boolean!`

```
public Boolean isAllowed() {
    return this.isAllowed;
  }
```

When I just start the Application everything works without any Issues. It seems the `SchemaMappingInspector` is only used in Mvc-Tests?

## Expected behavior
A schema that works without issues in DGS should also be correctly validated by spring-graphql within tests. Or there should be an option to disable the `SchemaMappingInspector` in Tests.

## Actual behavior
I get the following Exception when I start the test.
```
Caused by: java.lang.IllegalArgumentException: Method must not be null
	at org.springframework.util.Assert.notNull(Assert.java:172)
	at org.springframework.core.MethodParameter.<init>(MethodParameter.java:128)
	at org.springframework.core.MethodParameter.<init>(MethodParameter.java:114)
	at org.springframework.graphql.execution.SchemaMappingInspector.checkFieldsContainer(SchemaMappingInspector.java:184)
	at org.springframework.graphql.execution.SchemaMappingInspector.checkField(SchemaMappingInspector.java:254)
	at org.springframework.graphql.execution.SchemaMappingInspector.checkFieldsContainer(SchemaMappingInspector.java:185)
	at org.springframework.graphql.execution.SchemaMappingInspector.checkField(SchemaMappingInspector.java:254)
	at org.springframework.graphql.execution.SchemaMappingInspector.checkFieldsContainer(SchemaMappingInspector.java:173)
	at org.springframework.graphql.execution.SchemaMappingInspector.checkField(SchemaMappingInspector.java:254)
	at org.springframework.graphql.execution.SchemaMappingInspector.checkFieldsContainer(SchemaMappingInspector.java:185)
	at org.springframework.graphql.execution.SchemaMappingInspector.checkField(SchemaMappingInspector.java:254)
	at org.springframework.graphql.execution.SchemaMappingInspector.checkFieldsContainer(SchemaMappingInspector.java:173)
	at org.springframework.graphql.execution.SchemaMappingInspector.checkField(SchemaMappingInspector.java:254)
	at org.springframework.graphql.execution.SchemaMappingInspector.checkFieldsContainer(SchemaMappingInspector.java:173)
	at org.springframework.graphql.execution.SchemaMappingInspector.checkSchemaFields(SchemaMappingInspector.java:139)
	at org.springframework.graphql.execution.SchemaMappingInspector.getOrCreateReport(SchemaMappingInspector.java:130)
	at org.springframework.graphql.execution.SchemaMappingInspector$DefaultInitializer.inspect(SchemaMappingInspector.java:447)
	at org.springframework.graphql.execution.SchemaMappingInspector.inspect(SchemaMappingInspector.java:317)
	at com.netflix.graphql.dgs.springgraphql.DgsGraphQLSourceBuilder.setupSchemaReporter$lambda$2(DgsGraphQLSourceBuilder.kt:152)
```

**Comment by paulbakker** [comment]
@colomdan I've been trying to reproduce this issue, but haven't been able to.
Could you give some instructions how to trigger this issue?

**Comment by colomdan** [comment]
Hi @paulbakker 

Thank you for your reply.

I created an example project from scratch:
[example-project](https://github.com/colomdan/dgs-schema-validation-example)

With the latest Spring version, the SchemaMappingInspector no longer throws exceptions. However, it still incorrectly classifies the ‘allowed’ field as an unmapped field, even though I can query it using GraphiQL.

```
2025-01-20T11:53:33.134+01:00  INFO 19404 --- [demo] [           main] .d.s.a.DgsSpringGraphQLAutoConfiguration : ***Schema Report***
Unmapped fields: [UserConfig.allowed, Query._service]
Unmapped registrations: {}
Unmapped arguments: []
Skipped types: []
```

Since no exception is thrown anymore, it is not a big problem for us, but it is probably still not ideal that Spring classifies ‘allowed’ as an unmapped field, even I can query it with DGS.

**Comment by paulbakker** [comment]
I tested this a bit further and found the following:

1. This happens both for tests and regular startup
2. It's only for boolean methods named `is*` instead of `get*`
3. The is in Spring Graphql (using a property detection mechanism from Spring Framework). 

I've created an issue about this in the Spring GraphQL repository: https://github.com/spring-projects/spring-graphql/issues/1332

Since this is not actionable at the DGS side, I'll close the issue here. Thanks for the code example, this helped spotting the issue.
