### ISSUE TITLE
feature: Add subscription support to WebFlux applications

### ISSUE THREAD

**Issue by hantsy** [Netflix/dgs-framework#401]
I created a WebFlux application and add the following dependencies:

https://github.com/hantsy/spring-graphql-sample/tree/master/dgs-webflux

```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>

        <dependency>
            <groupId>com.netflix.graphql.dgs</groupId>
            <artifactId>graphql-dgs-webflux-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>com.netflix.graphql.dgs</groupId>
            <artifactId>graphql-dgs-subscriptions-websockets-autoconfigure</artifactId>
        </dependency>

```

## Expected behavior

WebFlux application should work without WebMvc .

## Actual behavior

Dependent on WebMvc

## Steps to reproduce

When running the application, I got the following exception.

```bash
2021-06-13 19:23:27.241 ERROR 15456 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Error processing condition on com.netflix.graphql.dgs.webflux.autoconfiguration.DgsWebFluxAutoConfiguration.reactiveGraphQlContextBuilder
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:193) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:153) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:343) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1336) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325) ~[spring-boot-2.5.0.jar:2.5.0]
	at com.example.demo.DemoApplication.main(DemoApplication.java:10) ~[classes/:na]
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.springframework.web.socket.config.annotation.WebSocketConfigurationSupport] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@1d44bcfa]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481) ~[spring-core-5.3.7.jar:5.3.7]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:358) ~[spring-core-5.3.7.jar:5.3.7]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:371) ~[spring-core-5.3.7.jar:5.3.7]
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:414) ~[spring-core-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$2(AbstractAutowireCapableBeanFactory.java:747) ~[spring-beans-5.3.7.jar:5.3.7]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:746) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:685) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:656) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1670) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:570) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:542) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:238) ~[spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:231) ~[spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:221) ~[spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:169) ~[spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:144) ~[spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	... 17 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/web/servlet/HandlerMapping
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3334) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2446) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463) ~[spring-core-5.3.7.jar:5.3.7]
	... 34 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.web.servlet.HandlerMapping
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[na:na]
	... 38 common frames omitted

```

**Comment by berngp** [comment]
@hantsy we don't yet support `graphql-dgs-subscriptions-websockets-autoconfigure` with WebFlux. If you remove the dependency you should be able to start your application.

**Comment by hantsy** [comment]
OK, thanks for pointing out this.

As mentioned in #236, hope the SSE/WebSocket are implemented by MVC and WebFlux respectively, and hidden the implementation for developers. Like the `tcp` and `websocket` support in Spring RSocket, hope the `Subscription` implementation just provides a simple configuration and some `xxxCustomizer` for developers.

```properties
dgs.subscritpion.protocol=http // or websocket
dgs.subscription.http.endpoint=/graphql/sse
dgs.subscription.http.connect-timeout=30000
```

**Comment by hantsy** [comment]
Created a simple Subscription example, https://github.com/hantsy/spring-graphql-sample/tree/master/dgs-subscription-ws, it lacks a web client here(I will create it).
I am not sure if it works with Angular GraphQL,  https://apollo-angular.com/docs/data/subscriptions.

**Comment by paulbakker** [comment]
Websocket subscriptions has been there from the initial release with Webflux, and it's just part of the main Webflux module, not a separate module.

https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-spring-webflux-autoconfigure/src/main/kotlin/com/netflix/graphql/dgs/webflux/handlers/DgsReactiveWebsocketHandler.kt

I'm closing this, assuming this is not actually an issue. Please re-open if that turns out to be false.

**Comment by itsandreramon** [comment]
I am still getting this error unfortunately. 

```groovy
dependencies {
    implementation(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:4.8.3"))
    implementation("com.netflix.graphql.dgs:graphql-dgs-webflux-starter")

    implementation("org.springframework.boot:spring-boot-starter-webflux")
    // ...
}
```

```kotlin
@DgsComponent
class SymbolFetcher(private val symbolService: SymbolService) {

    @DgsSubscription
    fun observeSymbolByName(name: String): Publisher<Symbol> {
        return symbolService.observeByName(name)
    }
}
```

```
2021-10-05T13:18:38.587879089Z 2021-10-05 13:18:38.577  INFO 1 --- [           main] de.thb.spring.AppKt                      : Starting AppKt using Java 11.0.12 on b39fefb53f5b with PID 1 (/workspace/BOOT-INF/classes started by cnb in /workspace)
2021-10-05T13:18:38.592194756Z 2021-10-05 13:18:38.591  INFO 1 --- [           main] de.thb.spring.AppKt                      : No active profile set, falling back to default profiles: default
2021-10-05T13:18:43.440512550Z 2021-10-05 13:18:43.437 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
2021-10-05T13:18:43.440551883Z 
2021-10-05T13:18:43.440554633Z java.lang.IllegalStateException: Error processing condition on com.netflix.graphql.dgs.webflux.autoconfiguration.DgsWebFluxAutoConfiguration.reactiveGraphQlContextBuilder
2021-10-05T13:18:43.440556675Z 	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[spring-boot-autoconfigure-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.440558717Z 	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440568383Z 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:193) ~[spring-context-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440570508Z 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:153) ~[spring-context-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440580967Z 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129) ~[spring-context-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440582967Z 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:343) ~[spring-context-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440584758Z 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[spring-context-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440586550Z 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[spring-context-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440588383Z 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[spring-context-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440590842Z 	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[spring-context-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440592633Z 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440594383Z 	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64) ~[spring-boot-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.440596133Z 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.440597800Z 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.440599508Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.440601383Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.440603050Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.440604717Z 	at de.thb.spring.AppKt.main(App.kt:39) ~[classes/:na]
2021-10-05T13:18:43.440606383Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2021-10-05T13:18:43.440608050Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
2021-10-05T13:18:43.440609675Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
2021-10-05T13:18:43.440611342Z 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
2021-10-05T13:18:43.440612925Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[workspace/:na]
2021-10-05T13:18:43.440616800Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[workspace/:na]
2021-10-05T13:18:43.440618550Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[workspace/:na]
2021-10-05T13:18:43.440620175Z 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[workspace/:na]
2021-10-05T13:18:43.440621842Z Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.springframework.web.socket.config.annotation.DelegatingWebSocketConfiguration] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@18e8568]
2021-10-05T13:18:43.440623925Z 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481) ~[spring-core-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440625633Z 	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:358) ~[spring-core-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440627342Z 	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:414) ~[spring-core-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440629092Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$2(AbstractAutowireCapableBeanFactory.java:765) ~[spring-beans-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440630883Z 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source) ~[na:na]
2021-10-05T13:18:43.440632550Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:764) ~[spring-beans-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440634383Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:703) ~[spring-beans-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440636342Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:674) ~[spring-beans-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440638217Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1670) ~[spring-beans-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440639967Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:570) ~[spring-beans-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440641758Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:542) ~[spring-beans-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440643508Z 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:238) ~[spring-boot-autoconfigure-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.440645342Z 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:231) ~[spring-boot-autoconfigure-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.440647217Z 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:221) ~[spring-boot-autoconfigure-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.440649008Z 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:169) ~[spring-boot-autoconfigure-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.440652925Z 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:144) ~[spring-boot-autoconfigure-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.440654717Z 	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.440656467Z 	... 25 common frames omitted
2021-10-05T13:18:43.440658008Z Caused by: java.lang.NoClassDefFoundError: org/springframework/web/servlet/HandlerMapping
2021-10-05T13:18:43.440659633Z 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
2021-10-05T13:18:43.440661300Z 	at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[na:na]
2021-10-05T13:18:43.440662967Z 	at java.base/java.lang.Class.getDeclaredMethods(Unknown Source) ~[na:na]
2021-10-05T13:18:43.440664592Z 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463) ~[spring-core-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.440666467Z 	... 41 common frames omitted
2021-10-05T13:18:43.440668008Z Caused by: java.lang.ClassNotFoundException: org.springframework.web.servlet.HandlerMapping
2021-10-05T13:18:43.440669633Z 	at java.base/java.net.URLClassLoader.findClass(Unknown Source) ~[na:na]
2021-10-05T13:18:43.440671217Z 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
2021-10-05T13:18:43.440672842Z 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:135) ~[workspace/:na]
2021-10-05T13:18:43.440674508Z 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
2021-10-05T13:18:43.440676050Z 	... 45 common frames omitted
2021-10-05T13:18:43.440677592Z 
2021-10-05T13:18:43.489594383Z 2021-10-05 13:18:43.488  WARN 1 --- [           main] o.s.boot.SpringApplication               : Unable to close ApplicationContext
2021-10-05T13:18:43.489629258Z 
2021-10-05T13:18:43.489632050Z java.lang.IllegalStateException: Failed to introspect Class [org.springframework.web.socket.config.annotation.DelegatingWebSocketConfiguration] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@18e8568]
2021-10-05T13:18:43.489634133Z 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481) ~[spring-core-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.489636258Z 	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:358) ~[spring-core-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.489637967Z 	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:414) ~[spring-core-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.489639717Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$2(AbstractAutowireCapableBeanFactory.java:765) ~[spring-beans-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.489649925Z 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source) ~[na:na]
2021-10-05T13:18:43.489651758Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:764) ~[spring-beans-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.489653592Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:703) ~[spring-beans-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.489655467Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:674) ~[spring-beans-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.489657217Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1670) ~[spring-beans-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.489659133Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:570) ~[spring-beans-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.489660967Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:542) ~[spring-beans-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.489663300Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:667) ~[spring-beans-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.489665092Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:659) ~[spring-beans-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.489666842Z 	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1300) ~[spring-context-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.489668592Z 	at org.springframework.boot.SpringApplication.getExitCodeFromMappedException(SpringApplication.java:886) ~[spring-boot-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.489670342Z 	at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:874) ~[spring-boot-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.489672258Z 	at org.springframework.boot.SpringApplication.handleExitCode(SpringApplication.java:861) ~[spring-boot-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.489673967Z 	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:802) ~[spring-boot-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.489675842Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:348) ~[spring-boot-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.489677550Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.489679425Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.5.jar:2.5.5]
2021-10-05T13:18:43.489681050Z 	at de.thb.spring.AppKt.main(App.kt:39) ~[classes/:na]
2021-10-05T13:18:43.489682675Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2021-10-05T13:18:43.489684508Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
2021-10-05T13:18:43.489688300Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
2021-10-05T13:18:43.489690050Z 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
2021-10-05T13:18:43.489691717Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[workspace/:na]
2021-10-05T13:18:43.489693383Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[workspace/:na]
2021-10-05T13:18:43.489695217Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[workspace/:na]
2021-10-05T13:18:43.489696967Z 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[workspace/:na]
2021-10-05T13:18:43.489698633Z Caused by: java.lang.NoClassDefFoundError: org/springframework/web/servlet/HandlerMapping
2021-10-05T13:18:43.489700300Z 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
2021-10-05T13:18:43.489701925Z 	at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[na:na]
2021-10-05T13:18:43.489703758Z 	at java.base/java.lang.Class.getDeclaredMethods(Unknown Source) ~[na:na]
2021-10-05T13:18:43.489705342Z 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463) ~[spring-core-5.3.10.jar:5.3.10]
2021-10-05T13:18:43.489707050Z 	... 29 common frames omitted
2021-10-05T13:18:43.489708633Z Caused by: java.lang.ClassNotFoundException: org.springframework.web.servlet.HandlerMapping
2021-10-05T13:18:43.489710300Z 	at java.base/java.net.URLClassLoader.findClass(Unknown Source) ~[na:na]
2021-10-05T13:18:43.489711883Z 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
2021-10-05T13:18:43.489713508Z 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:135) ~[workspace/:na]
2021-10-05T13:18:43.489715175Z 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
2021-10-05T13:18:43.489716717Z 	... 33 common frames omitted
```

**Comment by hwhh** [comment]
Is there any way one can access the sessions object in the WebsocketGraphQLWSProtocolHandler? I want to be able to use ReactiveSecurityContextHolder or similar in order to get the currently connected user information
