### ISSUE TITLE
feature: Compatibility with Graphlql-Java 17.0

### ISSUE THREAD

**Issue by EugenMayer** [Netflix/dgs-framework#585]
When using GraphQL 17.0 (early adoption) i get this exception

```
Caused by: java.lang.NoSuchMethodError: graphql/schema/GraphQLScalarType.<init>(Ljava/lang/String;Ljava/lang/String;Lgraphql/schema/Coercing;)V (loaded from file:/home/em/.gradle/caches/modules-2/files-2.1/com.graphql-java/graphql-java/17.0/468bba01653addd61974f613acd3302b8f4de016/graphql-java-17.0.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@55a01191) called from class graphql.scalars.datetime.DateTimeScalar (loaded from file:/home/em/.gradle/caches/modules-2/files-2.1/com.graphql-java/graphql-java-extended-scalars/16.0.1/3fbea67b145034b91f6d6c0c95d0303d3f894749/graphql-java-extended-scalars-16.0.1.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@55a01191).
	at graphql.scalars.datetime.DateTimeScalar.<init>(DateTimeScalar.java:27)
	at graphql.scalars.ExtendedScalars.<clinit>(ExtendedScalars.java:42)
	at com.netflix.graphql.dgs.autoconfig.DgsExtendedScalarsAutoConfiguration$TimeExtendedScalarsAutoConfiguration$timesExtendedScalarsRegistrar$1.getScalars(DgsExtendedScalarsAutoConfiguration.kt:52)
	at com.netflix.graphql.dgs.autoconfig.DgsExtendedScalarsAutoConfiguration$AbstractExtendedScalarRegistrar.addScalar(DgsExtendedScalarsAutoConfiguration.kt:147)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider.invokeDgsRuntimeWiring(DgsSchemaProvider.kt:204)
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider.schema(DgsSchemaProvider.kt:140)
	at com.netflix.graphql.dgs.autoconfig.DgsAutoConfiguration.schema(DgsAutoConfiguration.kt:158)
	at com.netflix.graphql.dgs.autoconfig.DgsAutoConfiguration$$EnhancerBySpringCGLIB$$f5587fa0.CGLIB$schema$6(<generated>)
```

According to https://github.com/graphql-java/graphql-java/releases/tag/v17.0 it relates to `Non standard scalars have been removed`.

Maybe we can start an adoption here?

**Comment by EugenMayer** [comment]
Using 4.8.3 this issue seem to have been resolved, while a new spawned #666 

IMHO this issue can be closed.

**Comment by EugenMayer** [comment]
With 4.9.0 graphQL is working perfectly. To cleanup you issues i take the liberty to close this issue myself. Let me know if that was a mistake :)
