### ISSUE TITLE
bug: GraphQL 17.0 support fails with 4.8.3

### ISSUE THREAD

**Issue by EugenMayer** [Netflix/dgs-framework#666]
Using 4.8.3 with spring boot 2.5.4.

Also using scalars:
- `com.netflix.graphql.dgs:graphql-dgs-extended-scalars`
- `com.graphql-java:graphql-java:17.3`
- `com.graphql-java:graphql-java-extended-scalars:17.0`

Getting this exception in my tests

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'schema' threw exception; nested exception is java.lang.NoSuchMethodError: 'java.lang.Object graphql.schema.GraphQLArgument.getDefaultValue()'
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 73 more
Caused by: java.lang.NoSuchMethodError: 'java.lang.Object graphql.schema.GraphQLArgument.getDefaultValue()'
	at com.apollographql.federation.graphqljava.FederationSdlPrinter.argsString(FederationSdlPrinter.java:777)
	at com.apollographql.federation.graphqljava.FederationSdlPrinter.lambda$printFieldDefinitions$2(FederationSdlPrinter.java:489)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.apollographql.federation.graphqljava.FederationSdlPrinter.printFieldDefinitions(FederationSdlPrinter.java:481)
	at com.apollographql.federation.graphqljava.FederationSdlPrinter.lambda$objectPrinter$5(FederationSdlPrinter.java:605)
	at com.apollographql.federation.graphqljava.FederationSdlPrinter.printType(FederationSdlPrinter.java:982)
	at com.apollographql.federation.graphqljava.FederationSdlPrinter.lambda$printType$16(FederationSdlPrinter.java:977)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.apollographql.federation.graphqljava.FederationSdlPrinter.printType(FederationSdlPrinter.java:977)
	at com.apollographql.federation.graphqljava.FederationSdlPrinter.print(FederationSdlPrinter.java:384)
	at com.apollographql.federation.graphqljava.SchemaTransformer.sdl(SchemaTransformer.java:208)
	at com.apollographql.federation.graphqljava.SchemaTransformer.build(SchemaTransformer.java:84)
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider.schema(DgsSchemaProvider.kt:120)
	at com.netflix.graphql.dgs.autoconfig.DgsAutoConfiguration.schema(DgsAutoConfiguration.kt:169)
	at com.netflix.graphql.dgs.autoconfig.DgsAutoConfiguration$$EnhancerBySpringCGLIB$$fda8905e.CGLIB$schema$3(<generated>)
	at com.netflix.graphql.dgs.autoconfig.DgsAutoConfiguration$$EnhancerBySpringCGLIB$$fda8905e$$FastClassBySpringCGLIB$$914b642d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.netflix.graphql.dgs.autoconfig.DgsAutoConfiguration$$EnhancerBySpringCGLIB$$fda8905e.schema(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
```

seems to be related to `apollographql`. If of any interested, does neither work with `17.0` (- `com.graphql-java:graphql-java:17.3`)

**Comment by EugenMayer** [comment]
Using `com.apollographql.federation:federation-graphql-java-support:0.7.0` fixes this issue

**Comment by EugenMayer** [comment]
As i see it already has been fixed https://github.com/Netflix/dgs-framework/blob/master/buildSrc/src/main/kotlin/Versions.kt#L25 so i guess 4.8.3 (as not announced) is yet not officially graphql 17 ready, right?

I guess this issue can be closed then (and taken at least as a signal that the new upcoming version with gql 17 works for us). Sorry for the noise!

**Comment by paulbakker** [comment]
Yeah we merged the upgrade but haven't released yet. That will happen in the next day or so.
