### ISSUE TITLE
bug: DgsInvalidInputArgumentException when mapping Int to Java Long type

### ISSUE THREAD

**Issue by carmas-RatedPower** [Netflix/dgs-framework#680]
Hi, using version `4.9.0` I am getting `DgsInvalidInputArgumentException` when performing a mutation. In my schema file, I have defined an input like:
```
input RowFinancial {
    rowId: ID!
    name: String!
    quantity: Int!
    tax: Float!
    price: Float!
}
```
Its `@InputArgument` Java Class is:

```
public class RowFinancial {

    private String rowId;
    private String name;
    private Long quantity;
    private Double tax;
    private Double price;
    // getters and setters
}
```

I am aware that the Java Long type is not part of the GraphQL spec (and is deprecated in the `Scalars` implementation), so I included the `graphql-dgs-extended-scalars` library and registered the scalar as follows:

```
@DgsComponent
public class LongScalarRegistration {

    @DgsRuntimeWiring
    public RuntimeWiring.Builder addScalar(RuntimeWiring.Builder builder) {
        return builder.scalar(ExtendedScalars.GraphQLLong);
    }

}
```

But when calling the mutation I'm getting the following error:
```
com.netflix.graphql.dgs.exceptions.DgsInvalidInputArgumentException: Invalid input argument `1` for field `quantity` on type `com.example.integration.demo.RowFinancial`
	at com.netflix.graphql.dgs.internal.InputObjectMapper.trySetField(InputObjectMapper.kt:152) ~[graphql-dgs-4.9.0.jar:4.9.0]
	at com.netflix.graphql.dgs.internal.InputObjectMapper.mapToJavaObject(InputObjectMapper.kt:127) ~[graphql-dgs-4.9.0.jar:4.9.0]
	at com.netflix.graphql.dgs.internal.InputObjectMapper.mapToJavaObject(InputObjectMapper.kt:112) ~[graphql-dgs-4.9.0.jar:4.9.0]
	at com.netflix.graphql.dgs.internal.InputObjectMapper.convertList(InputObjectMapper.kt:206) ~[graphql-dgs-4.9.0.jar:4.9.0]
	at com.netflix.graphql.dgs.internal.InputObjectMapper.mapToJavaObject(InputObjectMapper.kt:117) ~[graphql-dgs-4.9.0.jar:4.9.0]
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.convertValue(DataFetcherInvoker.kt:241) ~[graphql-dgs-4.9.0.jar:4.9.0]
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.processInputArgument(DataFetcherInvoker.kt:208) ~[graphql-dgs-4.9.0.jar:4.9.0]
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.invokeDataFetcher(DataFetcherInvoker.kt:62) ~[graphql-dgs-4.9.0.jar:4.9.0]
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider.createBasicDataFetcher$lambda-19(DgsSchemaProvider.kt:303) ~[graphql-dgs-4.9.0.jar:4.9.0]
	at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:87) ~[graphql-java-17.3.jar:na]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:279) ~[graphql-java-17.3.jar:na]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:210) ~[graphql-java-17.3.jar:na]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:182) ~[graphql-java-17.3.jar:na]
	at graphql.execution.AsyncSerialExecutionStrategy.lambda$execute$1(AsyncSerialExecutionStrategy.java:43) ~[graphql-java-17.3.jar:na]
	at graphql.execution.Async.eachSequentiallyImpl(Async.java:80) ~[graphql-java-17.3.jar:na]
	at graphql.execution.Async.eachSequentially(Async.java:69) ~[graphql-java-17.3.jar:na]
	at graphql.execution.AsyncSerialExecutionStrategy.execute(AsyncSerialExecutionStrategy.java:38) ~[graphql-java-17.3.jar:na]
	at graphql.execution.Execution.executeOperation(Execution.java:159) ~[graphql-java-17.3.jar:na]
	at graphql.execution.Execution.execute(Execution.java:105) ~[graphql-java-17.3.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:613) ~[graphql-java-17.3.jar:na]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:538) ~[graphql-java-17.3.jar:na]
	at graphql.GraphQL.executeAsync(GraphQL.java:502) ~[graphql-java-17.3.jar:na]
	at com.netflix.graphql.dgs.internal.BaseDgsQueryExecutor.baseExecute(DefaultDgsQueryExecutor.kt:233) ~[graphql-dgs-4.9.0.jar:4.9.0]
	at com.netflix.graphql.dgs.internal.DefaultDgsQueryExecutor.execute(DefaultDgsQueryExecutor.kt:80) ~[graphql-dgs-4.9.0.jar:4.9.0]
	at com.netflix.graphql.dgs.internal.DefaultDgsQueryExecutor.getJsonResult(DefaultDgsQueryExecutor.kt:157) ~[graphql-dgs-4.9.0.jar:4.9.0]
	at com.netflix.graphql.dgs.internal.DefaultDgsQueryExecutor.getJsonResult$default(DefaultDgsQueryExecutor.kt:156) ~[graphql-dgs-4.9.0.jar:4.9.0]
	at com.netflix.graphql.dgs.internal.DefaultDgsQueryExecutor.executeAndExtractJsonPath(DefaultDgsQueryExecutor.kt:107) ~[graphql-dgs-4.9.0.jar:4.9.0]
	at com.netflix.graphql.dgs.DgsQueryExecutor.executeAndExtractJsonPath(DgsQueryExecutor.java:103) ~[graphql-dgs-4.9.0.jar:4.9.0]
	at com.example.integration.demo.DemoApplicationTests.fails(DemoApplicationTests.java:36) ~[test-classes/:na]
```

When trying version `4.5.1` the same code executes without issue. I am wondering if I've missed some change or I'm taking the wrong approach.

Find attached a simple test case to reproduce the issue.
[test-case.zip](https://github.com/Netflix/dgs-framework/files/7293835/test-case.zip)

Kind regards.

**Comment by paulbakker** [comment]
Hi @carmas-RatedPower, you had a few mistakes in your test case that together caused this issue.
The first issue I found is that the schema file actually had `Int` defined for quantity. This means the Long scalar wouldn't be used, even if it was registered correctly.

After change the field to `Long`, the application failed to startup complaining that the scalar doesn't exist. I also had to add `scalar Long` to the schema file.

Again, the test would fail with an application startup failure, saying that there is no scalar implementation for Long. The reason for this was that in your test you specified 
```java
@SpringBootTest(classes = {DgsAutoConfiguration.class, TestMutation.class)
```

Note that the `LongRegistration` is missing from the list of classes!
So after fixing that, the test passes.

```
@SpringBootTest(classes = {DgsAutoConfiguration.class, TestMutation.class, LongScalarRegistration.class})
```
