### ISSUE TITLE
Upgrading to 3.5.1 gives ClassNotFoundException: net.minidev.json.writer.JsonReaderI

### ISSUE THREAD

**Issue by marceloverdijk** [Netflix/dgs-framework#81]
```
2021-02-23 17:22:55.585 ERROR 6480 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 
'requestMappingHandlerAdapter' defined in class path resource 
[org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: 
Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: 
Failed to instantiate [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]: Factory 
method 'requestMappingHandlerAdapter' threw exception; nested exception is java.lang.NoClassDefFoundError: 
net/minidev/json/writer/JsonReaderI
```

```
Caused by: java.lang.ClassNotFoundException: net.minidev.json.writer.JsonReaderI
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
        ... 45 common frames omitted
```

This happens when running `./gradlew clean bootRun` with a simple project using JDK 15.

Could this be related to [Exclude json-smart transitive dependency from json-path](https://github.com/Netflix/dgs-framework/commit/5fc87ecf310189587fb82d37bc82ef69308ee098)?

**Comment by paulbakker** [comment]
Yes it is, also reported here. https://github.com/Netflix/dgs-framework/issues/73
I'm re-opening the previous issue, closing this one as duplicate.
