### ISSUE TITLE
bug: 4.9.24 breaks Springboot context load when custom object mapper exists

### ISSUE THREAD

**Issue by onomesotu** [Netflix/dgs-framework#949]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.
Bumping the version to 4.9.24 caused the SpringBoot context to fail to start. 
The workaround is I have to annotate my bean with `@Primary` for this to be fixed. 

## Expected behavior
In version 4.9.21, configuring my own object mapper does not have any effect on DGS and the Spring context started without any issues. 
```java
@Bean
  public ObjectMapper getObjectMapper() {
    return new ObjectMapper()
        .findAndRegisterModules()
        .registerModule(jacksonDatabindModule)
        .setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
  }
```

## Actual behavior
Bumping the version to 4.9.24 (which adds a configurable object mapper for DGS) causes the Spring context to fail to start with the `NoUniqueBeanDefinitionException` error because SpringBoot now finds two beans for the object mapper. Stacktrace below. 
```java
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'com.fasterxml.jackson.databind.ObjectMapper' available: expected single matching bean but found 2: getObjectMapper,dgsObjectMapper
	at app//org.springframework.beans.factory.config.DependencyDescriptor.resolveNotUnique(DependencyDescriptor.java:220)
	at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1367)
	at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at app//org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at app//org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 280 more
```
## Steps to reproduce
Any SpringBoot version
- Define an object mapper bean config
- Add DGS dependencies 4.9.21
- Add code that requires injecting the object mapper
- The spring context starts alright. 

- Update the DGS version to 4.9.24
- Run the same code. 
- It should fail with the aforementioned error. 

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by srinivasankavitha** [comment]
Sorry, I should update the DGS docs with the setup. You basically need to
annotate with ***@***.***("dgsObjectMapper")` in your app's configuration
in order to override the default bean with the same name.
```
@Bean
@Qualifier("dgsObjectMapper")
open fun dgsObjectMapper(): ObjectMapper {

    val customMapper = jacksonObjectMapper()
    customMapper.registerModule(JavaTimeModule())
    return customMapper
}
```

**Comment by srinivasankavitha** [comment]
Updated docs as well - https://github.com/Netflix/dgs/pull/88
