### ISSUE TITLE
bug: GraphiQL does not work in Chrome Version 100.0.4896.127

### ISSUE THREAD

**Issue by hzariv** [Netflix/dgs-framework#987]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior
GraphiQL UI should render in Google Chrome browser

## Actual behavior
GraphiQL page in Chrome is empty and I see the following error in console

react-dom.production.min.js:120 SyntaxError: Unexpected token X in JSON at position 2302
    at JSON.parse (<anonymous>)
    at I.fetchSchema (GraphiQL.tsx:914:34)
    at I.componentDidMount (GraphiQL.tsx:395:12)
    at yi (react-dom.production.min.js:178:410)
    at wi (react-dom.production.min.js:178:185)
    at wk (react-dom.production.min.js:177:231)
    at Gk (react-dom.production.min.js:196:429)
    at qb (react-dom.production.min.js:195:309)
    at Ai (react-dom.production.min.js:189:39)
    at Xa (react-dom.production.min.js:79:182)

## Steps to reproduce
Use a sample spring boot application with dependency on Netflix DGS and start the server. In Chrome use URL http://localhost:8080/graphiql

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by srinivasankavitha** [comment]
Closing this issue since we cannot replicate. Please try with a newer version of Chrome.
